### PR TITLE
Add windows user tutorial for `MLWIC` install

### PR DESCRIPTION
**Pull request by Nova-Scotia**
This is a companion guide for Windows users having trouble installing the necessary packages to run `MLWIC` or getting `classify` to work. I hope it can be helpful. Edits are welcome.

### CODE REVIEW

**Comment by mikeyEcology** [comment]
Thank you for putting this together @Nova-Scotia ! Do you mind if I add a link to this on the MLWIC readme page?

**Comment by Nova-Scotia** [comment]
Of course, go ahead!

**Comment by mikeyEcology** [comment]
Great. Thank you. I added a link to this page in the readme.

**Comment by Nova-Scotia** [comment]
One last thing: I think the link on the MLWIC readme page goes to this conversation instead of the tutorial, which is here: https://github.com/mikeyEcology/MLWIC_examples/blob/master/MLWIC_Windows_Set_up.md       I could create a pull request but I figured it would be easier for you to just edit the link! :) thanks!

**Comment by mikeyEcology** [comment]
Thanks for the heads up. I just changed it.

**Pull request merged**
